services:
  streamlit_app_public:
    build:
      context: .
      dockerfile: ./Dockerfile_public
    restart: unless-stopped
    ports:
      - "8502:8502"
  streamlit_app_private:
    build:
      context: .
      dockerfile: ./Dockerfile_private
    restart: unless-stopped
  reverse_proxy:
    build:
      context: ./openidc
    restart: unless-stopped
    volumes:
      - ${SSL_CERT_CRT:-./cert/certificate.crt}:/usr/local/apache2/conf/server.crt
      - ${SSL_CERT_KEY:-./cert/certificate.key}:/usr/local/apache2/conf/server.key
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "80:80"
      - "443:443"
